"""income tables

Revision ID: 239db9cb7b64
Revises: a762340ecc39
Create Date: 2026-03-05 14:36:18.315441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239db9cb7b64'
down_revision = 'a762340ecc39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('income_date', sa.DateTime(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_income_income_date'), ['income_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_income_user_id'))
        batch_op.drop_index(batch_op.f('ix_income_timestamp'))
        batch_op.drop_index(batch_op.f('ix_income_income_date'))

    op.drop_table('income')
    # ### end Alembic commands ###
