"""income income_date

Revision ID: fa6953d918ec
Revises: 239db9cb7b64
Create Date: 2026-03-05 16:32:19.882213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6953d918ec'
down_revision = '239db9cb7b64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.alter_column('income_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_income_income_date'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_income_income_date'), ['income_date'], unique=False)
        batch_op.alter_column('income_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
